# Generated by Django 4.2.4 on 2024-01-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="author",),
    ]
